apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.Name }}
    namespace: {{ .Values.Namespace }}