apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "extensions"
      - "policy"
      - "monitoring.coreos.com"
    resources: 
      - "*"
    verbs: 
      - "*"

  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "*"
    verbs:
      - "*"

  - apiGroups:
      - "helm.toolkit.fluxcd.io"
    resources: 
      - "helmreleases"
    verbs: 
      - "*"

  - apiGroups:
      - "keda.sh"
    resources: 
      - "scaledobjects"
    verbs: 
      - "*"
