apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  {{- with .Values.runnerDeployment.replicas }}
  replicas:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    spec:
      {{- with .Values.runnerDeployment.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        - key: project
          operator: Equal
          value: system
          effect: NoSchedule
        - key: role
          operator: Equal
          value: system
          effect: NoSchedule

      nodeSelector:
        project: system

      {{- if (.Values.runnerDeployment.APICredentials.enabled) }}
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager      
      {{- end }}

      image: {{ .Values.image }}
      dockerdWithinRunnerContainer: false
      serviceAccountName: {{ .Values.Name }}

      {{- with .Values.runnerDeployment.organization }}
      organization:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runnerDeployment.group }}
      group:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runnerDeployment.repository }}
      repository:
        {{- toYaml . | nindent 8 }}
      {{- end }}